<?php
namespace  AV\SparqlBundle\Sparql;

/**
 * Created by PhpStorm.
 * User: LaFaucheuse
 * Date: 15/05/2017
 * Time: 11:36
 */
class sparqlSelect extends sparql
{
    private $select;

    public function addSelect($name){
        $this->select[] = $name;
    }

    public function removeSelect($pos){
        unset($pos,$this->param);
    }


    public function formatSelect(){
        $selectString = 'SELECT ';
        if (is_array($this->select)){
            foreach ($this->select as $string){
                $selectString .= $string. ' ';
            }
        }else
            $selectString = "*";

        return $selectString."\n";
    }

    public function getQuery()
    {
        $data = parent::getQuery(); // TODO: Change the autogenerated stub
        $selectString = $this->formatSelect();
        return $data["prefix"].$selectString.$data["where"].$data["group"].$data["order"].$data['limit'];
    }
}