home:
    path:     /
    defaults: { _controller: semappsBundle:Admin:home }
team:
    path:     /invite
    defaults: { _controller: semappsBundle:Admin:team }
settings:
    path:     /parametres
    defaults: { _controller: semappsBundle:Admin:settings }
orgaComponentForm:
    path:     /{uniqueComponentName}/form/{id}
    defaults: { _controller: semappsBundle:Organization:add}
    requirements:
      uniqueComponentName: 'organization'

orgaComponentFormWithoutId:
    path:     /{uniqueComponentName}/form
    defaults: { _controller: semappsBundle:Organization:add}
    requirements:
      uniqueComponentName: 'organization'

personComponentForm:
    path:     /{uniqueComponentName}/form/{id}
    defaults: { _controller: semappsBundle:Admin:add}
    requirements:
      uniqueComponentName: 'person'

personComponentFormWithoutId:
    path:     /{uniqueComponentName}/form
    defaults: { _controller: semappsBundle:Admin:add}
    requirements:
      uniqueComponentName: 'person'
componentDelete:
    path:     /component/{componentName}/delete
    defaults: { _controller: semappsBundle:Component:remove }

componentList:
    path:     /component/{componentName}/list
    defaults: { _controller: semappsBundle:Component:list}

componentForm:
    path:     /component/{componentName}/form
    defaults: { _controller: semappsBundle:Component:add}
site:
    path:     /sites
    defaults: { _controller: semappsBundle:SiteFederation:manageSite }
