userDelete:
    path:     /user/{userId}/delete
    defaults: { _controller: semappsBundle:Admin:userDelete }
userList:
    path:     /user/list
    defaults: { _controller: semappsBundle:Admin:listUser }
sendUser:
    path:     /user/{userId}/send/{nameRoute}
    defaults: { _controller: semappsBundle:Admin:sendUser }
changeAccess:
    path:    /access/{userId}/change/{roles}
    defaults: { _controller: semappsBundle:Admin:changeAccess }
orgaDelete:
    path:     /organization/{orgaId}/delete
    defaults: { _controller: semappsBundle:Organisation:orgaDelete }
orgaList:
    path:     /organization/list
    defaults: { _controller: semappsBundle:Organisation:all }
orgaExport:
    path:     /organization/export/csv
    defaults: { _controller: semappsBundle:Organisation:orgaExport }
