userDelete:
    path:     /user/{userId}/delete
    defaults: { _controller: semappsBundle:Admin:userDelete }
changeAccess:
    path:    /access/{userId}/change/{roles}
    defaults: { _controller: semappsBundle:Admin:changeAccess }
userList:
    path:     /user/list
    defaults: { _controller: semappsBundle:Admin:listUser }
sendUser:
    path:     /user/{userId}/send/{nameRoute}
    defaults: { _controller: semappsBundle:Admin:sendUser }

orgaDelete:
    path:     /organisation/{orgaId}/delete
    defaults: { _controller: semappsBundle:Organisation:orgaDelete }
orgaList:
    path:     /organisation/list
    defaults: { _controller: semappsBundle:Organisation:all }
orgaExport:
    path:     /organisation/export/csv
    defaults: { _controller: semappsBundle:Organisation:orgaExport }
