### webservice ###
# tested
webserviceParameters:
    path:     /parameters
    defaults: { _controller: semappsBundle:Webservice:parameters }
# tested
webserviceSearch:
    path:     /search
    defaults: { _controller: semappsBundle:Webservice:search }
# tested
webserviceFieldUriSearch:
    path:     /search/field-uri
    defaults: { _controller: semappsBundle:Webservice:fieldUriSearch }
# tested
webserviceFieldUriLabel:
    path:     /label/field-uri
    defaults: { _controller: semappsBundle:Webservice:fieldUriLabel }
# tested
webserviceDetail:
    path:     /detail
    defaults: { _controller: semappsBundle:Webservice:detail }

webserviceRessource:
    path:     /ressource
    defaults: { _controller: semappsBundle:Webservice:ressource }

webserviceChangeContext:
    path:    /context/change/{id}
    defaults: { _controller: semappsBundle:Webservice:changeContext }
