account:
    resource: "@coreBundle/Resources/config/routing/account.yml"
    prefix:   /mon-compte/
webservice:
    resource: "@coreBundle/Resources/config/routing/webservice.yml"
    prefix:   /webservice
administration:
    resource: "@coreBundle/Resources/config/routing/administration.yml"
    prefix:   /administration

### carto ###
index:
    path:     /
    defaults: { _controller: coreBundle:WebSite:index }
searchHome:
    path:     /rechercher
    defaults: { _controller: coreBundle:WebSite:index }

searchHomeEmpty:
    path:     /rechercher/
    defaults: { _controller: coreBundle:WebSite:index }

searchBuilding:
    path:     /rechercher/{building}/
    defaults: { _controller: coreBundle:WebSite:index }

searchBuildingTerm:
    path:     /rechercher/{building}/{term}
    defaults: { _controller: coreBundle:WebSite:index }
detail:
    path:     /detail
    defaults: { _controller: coreBundle:WebSite:index }
ressource:
    path:     /ressource
    defaults: { _controller: coreBundle:WebSite:index }
register:
    path:     /register/{token}
    defaults: { _controller: coreBundle:Administration:register }