account:
    resource: "@semappsBundle/Resources/config/routing/account.yml"
    prefix:   /mon-compte/
webservice:
    resource: "@semappsBundle/Resources/config/routing/webservice.yml"
    prefix:   /webservice
administration:
    resource: "@semappsBundle/Resources/config/routing/administration.yml"
    prefix:   /administration

### carto ###
index:
    path:     /
    defaults: { _controller: semappsBundle:WebSite:index }
searchBuildingTerm:
    path:     /rechercher/{term}
    defaults: { _controller: semappsBundle:WebSite:index,term: null }
detail:
    path:     /detail
    defaults: { _controller: semappsBundle:WebSite:index }
ressource:
    path:     /ressource
    defaults: { _controller: semappsBundle:WebSite:index }
register:
    path:     /register/{token}
    defaults: { _controller: semappsBundle:Administration:register }