### carto ###
index:
    path:     /
    defaults: { _controller: semappsBundle:WebSite:index }

searchHome:
    path:     /rechercher
    defaults: { _controller: semappsBundle:WebSite:index }

searchHomeEmpty:
    path:     /rechercher/
    defaults: { _controller: semappsBundle:WebSite:index }

searchBuilding:
    path:     /rechercher/{building}/
    defaults: { _controller: semappsBundle:WebSite:index }

searchBuildingTerm:
    path:     /rechercher/{building}/{term}
    defaults: { _controller: semappsBundle:WebSite:index }
detail:
    path:     /detail
    defaults: { _controller: semappsBundle:WebSite:index }

ressource:
    path:     /ressource
    defaults: { _controller: semappsBundle:WebSite:index }
programme:
    path:     /programme
    defaults: { _controller: semappsBundle:WebSite:index }
codeSocial:
    path:     /codeSocial
    defaults: { _controller: semappsBundle:WebSite:index }
infos:
    path:     /infos
    defaults: { _controller: semappsBundle:WebSite:index }
### administration ###
# admin Controller #
# tested
admin:
    path: /mon-compte
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /mon-compte/
        permanent: true
# tested
home:
    path:     /mon-compte/
    defaults: { _controller: semappsBundle:Admin:home }

register:
    path:     /register
    defaults: { _controller: semappsBundle:Admin:register }

user:
    path:     /user
    defaults: { _controller: semappsBundle:Admin:listUser }

sendUser:
    path:     /user/send/{userId}/{nameRoute}
    defaults: { _controller: semappsBundle:Admin:sendUser }
#
## tested
#fos_user_profile_show:
#    path:     /mon-compte/profile
#    defaults: { _controller: semappsBundle:Admin:profile }

# tested
team:
    path:     /mon-compte/invite
    defaults: { _controller: semappsBundle:Admin:team }
# tested
userDelete:
    path:     /mon-compte/user/delete/{userId}
    defaults: { _controller: semappsBundle:Admin:userDelete }

# tested
settings:
    path:     /parametres
    defaults: { _controller: semappsBundle:Admin:settings }

changeAccess:
    path:    /mon-compte/access/change/{userId}/{roles}
    defaults: { _controller: semappsBundle:Admin:changeAccess }

tab:
    path:     /orga/tab
    defaults: { _controller: semappsBundle:Admin:allOrganization }
food:
    path:     /mon-compte/food
    defaults: { _controller: semappsBundle:Admin:foodRecap }
# orga Controller #
all_orga:
    path:     /orga/all
    defaults: { _controller: semappsBundle:Organisation:all }

orgaExport:
    path:     /orga-export/csv
    defaults: { _controller: semappsBundle:Organisation:orgaExport }
#
## tested
#detail_orga:
#    path:     /orga/detail
#    defaults: { _controller: semappsBundle:Organisation:organisation }
## tested
#detail_orga_edit:
#    path:     /orga/detail/{orgaId}
#    defaults: { _controller: semappsBundle:Organisation:organisation }

orgaDelete:
    path:     /mon-compte/orga/delete/{orgaId}
    defaults: { _controller: semappsBundle:Organisation:orgaDelete }

orgaComponentForm:
    path:     /mon-compte/{uniqueComponentName}/form/{id}
    defaults: { _controller: semappsBundle:Organisation:add}
    requirements:
      uniqueComponentName: 'organisation'


orgaComponentFormWithoutId:
    path:     /mon-compte/{uniqueComponentName}/form
    defaults: { _controller: semappsBundle:Organisation:add}
    requirements:
      uniqueComponentName: 'organisation'


personComponentForm:
    path:     /mon-compte/{uniqueComponentName}/form/{id}
    defaults: { _controller: semappsBundle:Admin:add}
    requirements:
      uniqueComponentName: 'person'

personComponentFormWithoutId:
    path:     /mon-compte/{uniqueComponentName}/form
    defaults: { _controller: semappsBundle:Admin:add}
    requirements:
      uniqueComponentName: 'person'

# component Controller #
# tested
componentDelete:
    path:     /mon-compte/component/{componentName}/delete
    defaults: { _controller: semappsBundle:Component:remove }

componentList:
    path:     /mon-compte/component/{componentName}/list
    defaults: { _controller: semappsBundle:Component:list}

componentForm:
    path:     /mon-compte/component/{componentName}/form
    defaults: { _controller: semappsBundle:Component:add}

### webservice ###
# tested
webserviceParameters:
    path:     /webservice/parameters
    defaults: { _controller: semappsBundle:Webservice:parameters }
# tested
webserviceSearch:
    path:     /webservice/search
    defaults: { _controller: semappsBundle:Webservice:search }
# tested
webserviceFieldUriSearch:
    path:     /webservice/search/field-uri
    defaults: { _controller: semappsBundle:Webservice:fieldUriSearch }
# tested
webserviceFieldUriLabel:
    path:     /webservice/label/field-uri
    defaults: { _controller: semappsBundle:Webservice:fieldUriLabel }
# tested
webserviceDetail:
    path:     /webservice/detail
    defaults: { _controller: semappsBundle:Webservice:detail }

webserviceRessource:
    path:     /webservice/ressource
    defaults: { _controller: semappsBundle:Webservice:ressource }

### site ###
site:
    path:     /mon-compte/sites
    defaults: { _controller: semappsBundle:SiteFederation:manageSite }


