imports:
    - { resource: "@semappsBundle/Resources/config/SemanticForms/personConf.yml" }
    - { resource: "@semappsBundle/Resources/config/SemanticForms/organizationConf.yml" }
    - { resource: "@semappsBundle/Resources/config/SemanticForms/projectConf.yml" }
    - { resource: "@semappsBundle/Resources/config/SemanticForms/eventConf.yml" }
    - { resource: "@semappsBundle/Resources/config/SemanticForms/proposalConf.yml" }
    - { resource: "@semappsBundle/Resources/config/SemanticForms/documentConf.yml" }
    - { resource: "@semappsBundle/Resources/config/SemanticForms/documenttypeConf.yml" }
    - { resource: "@semappsBundle/Resources/config/SemanticForms/projecttypeConf.yml" }
    - { resource: "@semappsBundle/Resources/config/SemanticForms/eventtypeConf.yml" }
    - { resource: "@semappsBundle/Resources/config/SemanticForms/proposaltypeConf.yml" }
    - { resource: "@semappsBundle/Resources/config/SemanticForms/organizationtypeConf.yml" }
    - { resource: "@semappsBundle/Resources/config/SemanticForms/dbpedia.yml" }
    - { resource: "@semappsBundle/Resources/config/SemanticForms/thematicConf.yml" }
    - { resource: "@semappsBundle/Resources/config/SemanticForms/goodConf.yml" }
    - { resource: "@semappsBundle/Resources/config/SemanticForms/serviceConf.yml" }
    - { resource: "@semappsBundle/Resources/config/SemanticForms/placeConf.yml" }

parameters:
  typeToName:
    http://virtual-assembly.org/pair#Person: 'person'
    http://virtual-assembly.org/pair#Organization: 'organization'
    http://virtual-assembly.org/pair#Project: 'project'
    http://virtual-assembly.org/pair#Event: 'event'
    http://virtual-assembly.org/pair#Proposal: 'proposal'
    http://virtual-assembly.org/pair#Document: 'document'
    http://virtual-assembly.org/pair#Good: 'good'
    http://virtual-assembly.org/pair#Service: 'service'
    http://virtual-assembly.org/pair#Place: 'place'

  graphToName:
    urn://semapps/thesaurus/documenttype: 'documentType'
    urn://semapps/thesaurus/projecttype: 'projectType'
    urn://semapps/thesaurus/eventtype: 'eventType'
    urn://semapps/thesaurus/proposaltype: 'proposalType'
    urn://semapps/thesaurus/organizationtype: 'organizationType'
    http://assemblee-virtuelle.github.io/grands-voisins-v2/thesaurus.ttl: 'thematic'