imports:
    - { resource: "@semappsBundle/Resources/config/SemanticForms/personConf.yml" }
    - { resource: "@semappsBundle/Resources/config/SemanticForms/organizationConf.yml" }
    - { resource: "@semappsBundle/Resources/config/SemanticForms/projectConf.yml" }
    - { resource: "@semappsBundle/Resources/config/SemanticForms/eventConf.yml" }
    - { resource: "@semappsBundle/Resources/config/SemanticForms/proposalConf.yml" }
    - { resource: "@semappsBundle/Resources/config/SemanticForms/documentConf.yml" }
    - { resource: "@semappsBundle/Resources/config/SemanticForms/documenttypeConf.yml" }
    - { resource: "@semappsBundle/Resources/config/SemanticForms/projecttypeConf.yml" }
    - { resource: "@semappsBundle/Resources/config/SemanticForms/eventtypeConf.yml" }
    - { resource: "@semappsBundle/Resources/config/SemanticForms/proposaltypeConf.yml" }
    - { resource: "@semappsBundle/Resources/config/SemanticForms/dbpedia.yml" }

parameters:
  typeToName:
    http://virtual-assembly.org/pair#Person: 'person'
    http://virtual-assembly.org/pair#Organization: 'organization'
    http://virtual-assembly.org/pair#Project: 'project'
    http://virtual-assembly.org/pair#Event: 'event'
    http://virtual-assembly.org/pair#Proposal: 'proposal'
    http://virtual-assembly.org/pair#Document: 'document'
    http://virtual-assembly.org/pair#DocumentType: 'documentType'
    http://virtual-assembly.org/pair#ProjectType: 'projectType'
    http://virtual-assembly.org/pair#EventType: 'eventType'
    http://virtual-assembly.org/pair#ProposalType: 'proposalType'