services:

    semappsBundle.fileUploader:
        class: semappsBundle\Services\FileUploader
        arguments: ['%picture_directory%','%carto.domain%',]

    semappsBundle.encryption:
        class: semappsBundle\Services\Encryption
        arguments: ['%secret%']

    semappsBundle.sparqlRepository:
        class: semappsBundle\Services\SparqlRepository
        arguments: ['@semantic_forms.client',"@semappsBundle.confmanager"]

    semappsBundle.webserviceTools:
        class: semappsBundle\Services\WebserviceTools
        arguments: ['@doctrine.orm.entity_manager','@security.token_storage','@security.authorization_checker','@semappsBundle.confmanager','@semantic_forms.client']

    semappsBundle.contextManager:
        class: semappsBundle\Services\contextManager
        arguments: ['@semappsBundle.sparqlRepository','@doctrine.orm.entity_manager']

    semappsBundle.confmanager:
        class: semappsBundle\Services\confManager
        arguments: ['@service_container','%typetoname%','%graphtoname%']

    semappsBundle.importmanager:
        class: semappsBundle\Services\ImportManager
        arguments: ['@semantic_forms.client','@semappsBundle.sparqlRepository']
    semappsBundle.invitemanager:
        class: semappsBundle\Services\InviteManager
        arguments: ['@fos_user.util.token_generator']
#
#    semappsBundle.voter:
#        class: semappsBundle\Voters\ExampleVoter
#        arguments: ['@semappsBundle.sparqlRepository','@semantic_forms.client']
#        tags:
#          - { name: security.voter }
#        # small performance boost
#        public: false