services:
#    sparql.example:
#        class: VirtualAssembly\SparqlBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    sparqlbundle.client:
      class: VirtualAssembly\SparqlBundle\Services\SparqlClient