# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - mysql

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 7.1

# Define an environment variable
env:
  - SYMFONY_VERSION="3.0.*" DB=mysql

# Update composer
before-install:
  - composer self-update

# Install composer dependencies
install:
  - composer install

# Run script
script:
  - phpunit

# After a build, send email notification with the build results
notifications:
email: benoit.alessandroni@gmail.com
