semappsBundle\Entity\LinkUserOrga:
    type: entity
    table: null
    repositoryClass: semappsBundle\Repository\LinkUserOrgaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fkOrga:
            type: integer
        fkUser:
            type: integer
        roles:
            type: array
            column: Roles
    lifecycleCallbacks: {  }
