semappsBundle\Entity\Site:
    type: entity
    table: null
    repositoryClass: semappsBundle\Repository\SiteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        site:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
