imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@mmmfestBundle/Resources/config/services.yml" }
    - { resource: "@mmmfestBundle/Resources/config/SemanticForms/semanticforms.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    carto.domain: 'mmmfest.fr'
    picture_directory: '%kernel.root_dir%/../web/uploads/pictures'
    semantic_forms.prefixes:
        gvoi: "<http://assemblee-virtuelle.github.io/grands-voisins-v2/gv.owl.ttl#>"
    semantic_forms.fields_aliases:
        firstName: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#firstName"
        lastName: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#lastName" 			 
        alias: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#alias" 			    
        representedBy: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#representedBy" 	  
        description: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#description" 
        aboutPage: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#aboutPage" 	
        localizedBy: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#localizedBy" 		 
        email: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#e-mail" 			  
        phone: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#phone" 		
        hasInterest: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#hasInterest" 		
        knows: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#knows" 				
        memberOf: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#memberOf" 		
        responsibleOf: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#responsibleOf" 	   
        affiliatedTo: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#affiliatedTo"
        affiliates: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#affiliates"
        involvedIn: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#involvedIn"
        manages: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#manages" 		    
        offers: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#offers" 		    
        needs: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#needs" 				
        organizes: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#organizes" 		
        participantOf: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#participantOf"
        brainstorms: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#brainstorms"
        preferedLabel: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#preferedLabel"
        alternativeLabel: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#alternativeLabel"
        comment: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#comment"
        homePage: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#homePage"
        hasMember: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#hasMember"
        hasResponsible: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#hasResponsible"
        employs: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#employs"
        employedBy: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#employedBy"
        partnerOf: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#partnerOf"
        concretizes: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#concretizes"
        managedBy: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#managedBy"
        involves: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#involves"
        startDate: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#startDate"
        endDate: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#endDate"
        documentedBy: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#documentedBy"
        documents: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#documents"
        organizedBy: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#organizedBy"
        hasParticipant: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#hasParticipant"
        brainstormedBy: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#brainstormedBy"
        concretizedBy: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#concretizedBy"
        hasType: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#hasType"
        typeOf: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#typeOf"
        references: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#references"
        referencesBy: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#referencesBy"
        image: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#image"
        type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
        hostedIn: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#hostedIn"
        hasSubject: "http://assemblee-virtuelle.github.io/mmmfest/PAIR_temp.owl#hasSubject"
    fields_access:
        anonymous:
           # All
           - firstName
           - lastName
           - alias
           - representedBy
           - description
           - aboutPage
           - localizedBy
           - hasInterest
           - knows
           - memberOf
           - responsibleOf
           - affiliatedTo
           - affiliates
           - involvedIn
           - manages
           - offers
           - needs
           - organizes
           - participantOf
           - brainstorms
           - preferedLabel
           - alternativeLabel
           - comment
           - homePage
           - hasMember
           - hasResponsible
           - employs
           - employedBy
           - partnerOf
           - concretizes
           - managedBy
           - involves
           - startDate
           - endDate
           - documentedBy
           - documents
           - organizedBy
           - hasParticipant
           - brainstormedBy
           - concretizedBy
           - hasType
           - typeOf
           - references
           - referencesBy
           - image
           - type
           - hostedIn
           - hasSubject
        member:
           - email
           - phone
        super_admin:


framework:
    #esi:             ~
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        cookie_lifetime: 43200
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        special_alert: "%special_alert%"
    form_themes:
        - 'form/fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
                mmmfestBundle:
                    type: yml #On your case it should be annotation
                    dir: Resources/config/doctrine

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    auth_mode:  login
    encryption: ssl

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: mmmfestBundle\Entity\User
    from_email: #nouveau champs imposé par Symfony ou FOSUser
        address: noreply@lesgrandsvoisins.org
        sender_name: mmmfest
    registration:
        confirmation:
            template: email/content_email.email.twig
            enabled: false

# Liip configuration to resize picture
liip_imagine :
    resolvers :
        default :
            web_path : ~
    filter_sets :
        cache : ~
        # the name of the "filter set"
        profile :
            # adjust the image quality to 75%
            quality : 75
            # list of transformations to apply (the "filters")
            filters :
                # create a thumbnail: set size to 140x140 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail  : { size : [140, 140], mode : outbound }
        organisation:
            quality: 75
            filters:
                thumbnail: {size : [140, 140], mode: outbound}
