imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@GrandsVoisinsBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    gv.domain: 'dev.wexample.com'
    picture_directory: '%kernel.root_dir%/../web/uploads/pictures'
    semantic_forms.prefixes:
        gvoi: "<http://assemblee-virtuelle.github.io/grands-voisins-v2/gv.owl.ttl#>"
    semantic_forms.fields_aliases:
        type: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
        mbox: "http://xmlns.com/foaf/0.1/mbox"
        phone: "http://xmlns.com/foaf/0.1/phone"
        gvStatus: "http://assemblee-virtuelle.github.io/grands-voisins-v2/gv.owl.ttl#status"
        realisedContribution: "http://assemblee-virtuelle.github.io/grands-voisins-v2/gv.owl.ttl#realisedContribution"
        foafStatus: "http://xmlns.com/foaf/0.1/status"
        foafName: "http://xmlns.com/foaf/0.1/name"
        givenName: "http://xmlns.com/foaf/0.1/givenName"
        familyName: "http://xmlns.com/foaf/0.1/familyName"
        conventionType: "http://assemblee-virtuelle.github.io/grands-voisins-v2/gv.owl.ttl#conventionType"
        hasResponsible: "http://www.w3.org/ns/org#headOf"
        displayLabel: "urn:displayLabel"
        administrativeName: "http://assemblee-virtuelle.github.io/grands-voisins-v2/gv.owl.ttl#administrativeName"
        building: "http://assemblee-virtuelle.github.io/grands-voisins-v2/gv.owl.ttl#building"
        proposedContribution: "http://assemblee-virtuelle.github.io/grands-voisins-v2/gv.owl.ttl#proposedContribution"
        subject: "http://purl.org/dc/elements/1.1/subject"
        arrivalDate: "http://assemblee-virtuelle.github.io/grands-voisins-v2/gv.owl.ttl#arrivalDate"
        room: "http://assemblee-virtuelle.github.io/grands-voisins-v2/gv.owl.ttl#room"
        image: "http://xmlns.com/foaf/0.1/img"
        homepage : 'http://xmlns.com/foaf/0.1/homepage'
        empoyeesCount: 'http://assemblee-virtuelle.github.io/grands-voisins-v2/gv.owl.ttl#employeesCount'
        volunteeringProposals: 'http://assemblee-virtuelle.github.io/grands-voisins-v2/gv.owl.ttl#volunteeringProposals'
        description: 'http://assemblee-virtuelle.github.io/grands-voisins-v2/gv.owl.ttl#description'
        facebook: 'http://assemblee-virtuelle.github.io/grands-voisins-v2/gv.owl.ttl#facebook'
        twitter: 'http://assemblee-virtuelle.github.io/grands-voisins-v2/gv.owl.ttl#twitter'
        linkedin: 'http://assemblee-virtuelle.github.io/grands-voisins-v2/gv.owl.ttl#linkedin'
        topicInterest: 'http://xmlns.com/foaf/0.1/topic.interest'
        expertize: 'http://purl.org/ontology/cco/core#expertise'
        knows: 'http://xmlns.com/foaf/0.1/knows'
        memberOf: 'http://www.w3.org/ns/org#memberOf'
        slack: 'http://assemblee-virtuelle.github.io/grands-voisins-v2/gv.owl.ttl#slack'
    # Mixed fields from user / organization.
    fields_access:
        anonymous:
           # All
           - uri
           - type
           - foafName
           - image
           - homepage
           - facebook
           - twitter
           - linkedin
           # orga
           - hasResponsible
           - building
           - subject
           - description
           # person
           - displayLabel
           - givenName
           - familyName
           - topicInterest
           - expertize
           - knows
           - memberOf
        member:
           # all
           - mbox
           - phone
           # orga
           - room
           # person
           - slack
        super_admin:
           # orga
           - arrivalDate
           - gvStatus
           - administrativeName
           - conventionType
           - empoyeesCount
           - proposedContribution
           - realisedContribution

framework:
    #esi:             ~
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'form/fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
                GrandsVoisinsBundle:
                    type: yml #On your case it should be annotation
                    dir: Resources/config/doctrine

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    auth_mode:  login
    encryption: ssl

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: GrandsVoisinsBundle\Entity\User
    from_email: #nouveau champs imposé par Symfony ou FOSUser
        address: noreply@lesgrandsvoisins.org
        sender_name: Les Grands Voisins
    registration:
        confirmation:
            template: email/content_email.email.twig
            enabled: false

# Liip configuration to resize picture
liip_imagine :
    resolvers :
        default :
            web_path : ~
    filter_sets :
        cache : ~
        # the name of the "filter set"
        profile :
            # adjust the image quality to 75%
            quality : 75
            # list of transformations to apply (the "filters")
            filters :
                # create a thumbnail: set size to 140x140 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail  : { size : [140, 140], mode : outbound }
        organisation:
            quality: 75
            filters:
                thumbnail: {size : [140, 140], mode: outbound}
