grands_voisins:
    resource: "@GrandsVoisinsBundle/Resources/config/routing.yml"
    prefix:   /
# tested
grands_voisins_loader:
    resource: .
    type: component

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"


