security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_MEMBER:      ROLE_USER
        ROLE_EDITOR:      ROLE_MEMBER
        ROLE_ADMIN:       ROLE_EDITOR
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            http_basic: ~
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                require_previous_session: false
            logout:       true
            anonymous:    true
            remember_me:
                secret:   '%secret%'
                lifetime: 86400 # 1 week in seconds

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/confirm, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_NO_ACCESS }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mon-compte/, role: ROLE_MEMBER }
        - { path: ^/orga/detail, role: ROLE_MEMBER }
        - { path: ^/orga/save, role: ROLE_MEMBER }
        - { path: ^/orga/, role: ROLE_SUPER_ADMIN }
        - { path: ^/component/, role: ROLE_MEMBER }
        - { path: ^/component/new, role: ROLE_MEMBER }
        - { path: ^/user/send/, role: ROLE_ADMIN }
        - { path: ^/user, role: ROLE_SUPER_ADMIN }

