security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_MEMBER:      ROLE_USER
        ROLE_EDITOR:      ROLE_MEMBER
        ROLE_ADMIN:       ROLE_EDITOR
        ROLE_PATRON:      ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN,ROLE_PATRON

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/confirm, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_NO_ACCESS }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_MEMBER }
        - { path: ^/orga/, role: ROLE_MEMBER }
