security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_MEMBER:      ROLE_USER
        ROLE_EDITOR:      ROLE_MEMBER
        ROLE_ADMIN:       ROLE_EDITOR
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            http_basic: ~
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                require_previous_session: false
            logout:       true
            anonymous:    true
            remember_me:
                secret:   '%secret%'
                lifetime: 86400 # 1 week in seconds

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #account.yml
        - { path: ^/mon-compte/invite, role: ROLE_ADMIN }
        - { path: ^/mon-compte/person/form$, role: ROLE_MEMBER }
        - { path: '^/mon-compte/person/form/{0,9}', role: ROLE_SUPER_ADMIN }
        - { path: ^/mon-compte/organisation/form$, role: ROLE_MEMBER }
        - { path: '^/mon-compte/organisation/form/{0,9}', role: ROLE_SUPER_ADMIN }
        - { path: ^/mon-compte/invite, role: ROLE_ADMIN }
        - { path: ^/mon-compte/, role: ROLE_MEMBER }
        #administration.yml
        - { path: ^/administration/access, role: ROLE_ADMIN }
        - { path: ^/administration/user/list, role: ROLE_SUPER_ADMIN }
        - { path: ^/administration/user, role: ROLE_ADMIN }
        - { path: ^/administration, role: ROLE_SUPER_ADMIN }
