# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    semappsBundle.EventListener.ConfirmRegistration:
        class: semappsBundle\EventListener\ConfirmRegistrationListener
        arguments: ["@router", "@security.token_storage", "@doctrine.orm.entity_manager","@semantic_forms.client",'@semappsBundle.encryption']
        tags:
            - { name: kernel.event_subscriber }

    semappsBundle.EventListener.SendMail:
        class: semappsBundle\Services\Mailer
        arguments: ["@swiftmailer.mailer.default.transport.real", "%mailer_user%","@templating",'@semappsBundle.encryption',"%carto.domain%"]
