# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    mmmfestBundle.EventListener.ConfirmRegistration:
        class: mmmfestBundle\EventListener\ConfirmRegistrationListener
        arguments: ["@router", "@security.token_storage", "@doctrine.orm.entity_manager","@semantic_forms.client",'@mmmfestBundle.encryption']
        tags:
            - { name: kernel.event_subscriber }

    mmmfestBundle.EventListener.SendMail:
        class: mmmfestBundle\Services\Mailer
        arguments: ["@mailer", "@templating",'@mmmfestBundle.encryption']
