<?php

namespace GrandsVoisinsBundle\Repository;

/**
 * LinkUserOrgaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkUserOrgaRepository extends \Doctrine\ORM\EntityRepository
{
}
