### carto ###
index:
    path:     /
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

searchHome:
    path:     /rechercher
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

searchHomeEmpty:
    path:     /rechercher/
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

searchBuilding:
    path:     /rechercher/{building}/
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

searchBuildingTerm:
    path:     /rechercher/{building}/{term}
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }
detail:
    path:     /detail
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

ressource:
    path:     /ressource
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }
### administration ###
# admin Controller #
# tested
admin:
    path: /mon-compte
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /mon-compte/
        permanent: true
# tested
home:
    path:     /mon-compte/
    defaults: { _controller: GrandsVoisinsBundle:Admin:home }

register:
    path:     /register
    defaults: { _controller: GrandsVoisinsBundle:Admin:register }

user:
    path:     /user
    defaults: { _controller: GrandsVoisinsBundle:Admin:listUser }

sendUser:
    path:     /user/send/{userId}/{nameRoute}
    defaults: { _controller: GrandsVoisinsBundle:Admin:sendUser }

# tested
fos_user_profile_show:
    path:     /mon-compte/profile
    defaults: { _controller: GrandsVoisinsBundle:Admin:profile }

# tested
team:
    path:     /mon-compte/invite
    defaults: { _controller: GrandsVoisinsBundle:Admin:team }
# tested
userDelete:
    path:     /mon-compte/user/delete/{userId}
    defaults: { _controller: GrandsVoisinsBundle:Admin:userDelete }

# tested
settings:
    path:     /parametres
    defaults: { _controller: GrandsVoisinsBundle:Admin:settings }

changeAccess:
    path:    /mon-compte/access/change/{userId}/{roles}
    defaults: { _controller: GrandsVoisinsBundle:Admin:changeAccess }

tab:
    path:     /orga/tab
    defaults: { _controller: GrandsVoisinsBundle:Admin:allOrganization }


# orga Controller #
all_orga:
    path:     /orga/all
    defaults: { _controller: GrandsVoisinsBundle:Organisation:all }

orgaExport:
    path:     /orga-export/csv
    defaults: { _controller: GrandsVoisinsBundle:Organisation:orgaExport }

# tested
detail_orga:
    path:     /orga/detail
    defaults: { _controller: GrandsVoisinsBundle:Organisation:organisation }
# tested
detail_orga_edit:
    path:     /orga/detail/{orgaId}
    defaults: { _controller: GrandsVoisinsBundle:Organisation:organisation }

orgaDelete:
    path:     /mon-compte/orga/delete/{orgaId}
    defaults: { _controller: GrandsVoisinsBundle:Organisation:orgaDelete }

# component Controller #
# tested
componentDelete:
    path:     /mon-compte/component/delete
    defaults: { _controller: GrandsVoisinsBundle:Component:remove }

### webservice ###
# tested
webserviceParameters:
    path:     /webservice/parameters
    defaults: { _controller: GrandsVoisinsBundle:Webservice:parameters }
# tested
webserviceSearch:
    path:     /webservice/search
    defaults: { _controller: GrandsVoisinsBundle:Webservice:search }
# tested
webserviceFieldUriSearch:
    path:     /webservice/search/field-uri
    defaults: { _controller: GrandsVoisinsBundle:Webservice:fieldUriSearch }
# tested
webserviceFieldUriLabel:
    path:     /webservice/label/field-uri
    defaults: { _controller: GrandsVoisinsBundle:Webservice:fieldUriLabel }
# tested
webserviceDetail:
    path:     /webservice/detail
    defaults: { _controller: GrandsVoisinsBundle:Webservice:detail }

webserviceRessource:
    path:     /webservice/ressource
    defaults: { _controller: GrandsVoisinsBundle:Webservice:ressource }



