index:
    path:     /
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

searchHome:
    path:     /rechercher
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

searchBuilding:
    path:     /rechercher/{building}/
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

searchBuildingTerm:
    path:     /rechercher/{building}/{term}
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

detail:
    path:     /detail
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

admin:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin/
        permanent: true

home:
    path:     /admin/
    defaults: { _controller: GrandsVoisinsBundle:Admin:home }

profile:
    path:     /admin/profile
    defaults: { _controller: GrandsVoisinsBundle:Admin:profile }

sfProfile:
    path:     /admin/sfProfile
    defaults: { _controller: GrandsVoisinsBundle:Admin:userSFProfile }

saveSfProfile:
    path:     /admin/saveSfProfile
    defaults: { _controller: GrandsVoisinsBundle:Admin:userSaveSFProfile }

team:
    path:     /admin/invite
    defaults: { _controller: GrandsVoisinsBundle:Admin:team }

organisation:
    path:     /admin/organisation
    defaults: { _controller: GrandsVoisinsBundle:Admin:organisation }

saveOrganisation:
    path:     /admin/saveOrga
    defaults: { _controller: GrandsVoisinsBundle:Admin:saveOrganisation }

userDelete:
    path:     /admin/user/delete/{userId}
    defaults: { _controller: GrandsVoisinsBundle:Admin:userDelete }

webserviceBuilding:
    path:     /webservice/building
    defaults: { _controller: GrandsVoisinsBundle:Webservice:building }

webserviceSearch:
    path:     /webservice/search
    defaults: { _controller: GrandsVoisinsBundle:Webservice:search }

home_orga:
    path:     /orga/home
    defaults: { _controller: GrandsVoisinsBundle:Organisation:home }

new_orga:
    path:     /orga/new
    defaults: { _controller: GrandsVoisinsBundle:Organisation:new }
