grands_voisins_homepage:
    path:     /
    defaults: { _controller: GrandsVoisinsBundle:Default:index }

grands_voisins_homepage_search_all:
    path:     /search/all
    defaults: { _controller: GrandsVoisinsBundle:Default:search }

admin:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin/
        permanent: true

home:
    path:     /admin/
    defaults: { _controller: GrandsVoisinsBundle:Admin:home }

profile:
    path:     /admin/profile
    defaults: { _controller: GrandsVoisinsBundle:Admin:profile }

team:
    path:     /admin/invite
    defaults: { _controller: GrandsVoisinsBundle:Admin:team }

organisation:
    path:     /admin/organisation
    defaults: { _controller: GrandsVoisinsBundle:Admin:organisation }

userDelete:
    path:     /admin/user/delete/{userId}
    defaults: { _controller: GrandsVoisinsBundle:Admin:userDelete }

building:
    path:     /webservice/building
    defaults: { _controller: GrandsVoisinsBundle:Webservice:building }

search:
    path:     /webservice/search
    defaults: { _controller: GrandsVoisinsBundle:Webservice:search }
