index:
    path:     /
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

searchHome:
    path:     /rechercher
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

searchBuilding:
    path:     /rechercher/{building}/
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

searchBuildingTerm:
    path:     /rechercher/{building}/{term}
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

detail:
    path:     /detail
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

admin:
    path: /mon-compte
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /mon-compte/
        permanent: true

settings:
    path:     /parametres
    defaults: { _controller: GrandsVoisinsBundle:Admin:settings }

home:
    path:     /mon-compte/
    defaults: { _controller: GrandsVoisinsBundle:Admin:home }

profile:
    path:     /mon-compte/profile
    defaults: { _controller: GrandsVoisinsBundle:Admin:profile }

profileSave:
    path:     /mon-compte/profile/save
    defaults: { _controller: GrandsVoisinsBundle:Admin:profileSave }

team:
    path:     /mon-compte/invite
    defaults: { _controller: GrandsVoisinsBundle:Admin:team }

userDelete:
    path:     /mon-compte/user/delete/{userId}
    defaults: { _controller: GrandsVoisinsBundle:Admin:userDelete }

webserviceBuilding:
    path:     /webservice/building
    defaults: { _controller: GrandsVoisinsBundle:Webservice:building }

webserviceSearch:
    path:     /webservice/search
    defaults: { _controller: GrandsVoisinsBundle:Webservice:search }

webserviceDetail:
    path:     /webservice/detail
    defaults: { _controller: GrandsVoisinsBundle:Webservice:detail }

all_orga:
    path:     /orga/all
    defaults: { _controller: GrandsVoisinsBundle:Organisation:all }

detail_orga:
    path:     /orga/detail
    defaults: { _controller: GrandsVoisinsBundle:Organisation:newOrganisation }

save_orga:
    path:     /orga/save
    defaults: { _controller: GrandsVoisinsBundle:Organisation:saveOrganisation }

orgaDelete:
    path:     /mon-compte/orga/delete/{orgaId}
    defaults: { _controller: GrandsVoisinsBundle:Organisation:orgaDelete }

show_component:
    path:     /component/show/{uri}
    defaults: { _controller: GrandsVoisinsBundle:Component:show }

show_all_component:
    path:     /component/showAll
    defaults: { _controller: GrandsVoisinsBundle:Component:showAll }

show_all_spec_component:
    path:     /component/showAll/{type}
    defaults: { _controller: GrandsVoisinsBundle:Component:showAll }

save_component:
    path:     /component/save
    defaults: { _controller: GrandsVoisinsBundle:Component:save }

new_component:
    path:     /component/new/{type}
    defaults: { _controller: GrandsVoisinsBundle:Component:new }
