index:
    path:     /
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

searchHome:
    path:     /rechercher
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

searchBuilding:
    path:     /rechercher/{building}/
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

searchBuildingTerm:
    path:     /rechercher/{building}/{term}
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

detail:
    path:     /detail
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

admin:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin/
        permanent: true

home:
    path:     /admin/
    defaults: { _controller: GrandsVoisinsBundle:Admin:home }

profile:
    path:     /admin/profile
    defaults: { _controller: GrandsVoisinsBundle:Admin:profile }

profileSave:
    path:     /admin/profile/save
    defaults: { _controller: GrandsVoisinsBundle:Admin:profileSave }

team:
    path:     /admin/invite
    defaults: { _controller: GrandsVoisinsBundle:Admin:team }

userDelete:
    path:     /admin/user/delete/{userId}
    defaults: { _controller: GrandsVoisinsBundle:Admin:userDelete }

webserviceBuilding:
    path:     /webservice/building
    defaults: { _controller: GrandsVoisinsBundle:Webservice:building }

webserviceSearch:
    path:     /webservice/search
    defaults: { _controller: GrandsVoisinsBundle:Webservice:search }

webserviceDetail:
    path:     /webservice/detail
    defaults: { _controller: GrandsVoisinsBundle:Webservice:detail }

all_orga:
    path:     /orga/all
    defaults: { _controller: GrandsVoisinsBundle:Organisation:all }

detail_orga:
    path:     /orga/detail
    defaults: { _controller: GrandsVoisinsBundle:Organisation:newOrganisation }

save_orga:
    path:     /orga/save
    defaults: { _controller: GrandsVoisinsBundle:Organisation:saveOrganisation }

settings:
    path:     /parametres
    defaults: { _controller: GrandsVoisinsBundle:Organisation:settings }

