grands_voisins_homepage:
    path:     /
    defaults: { _controller: GrandsVoisinsBundle:Default:index }

grands_voisins_homepage_search_all:
    path:     /search/all
    defaults: { _controller: GrandsVoisinsBundle:Default:search }

admin:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin/
        permanent: true

home:
    path:     /admin/
    defaults: { _controller: GrandsVoisinsBundle:Admin:home }

profile:
    path:     /admin/profile
    defaults: { _controller: GrandsVoisinsBundle:Admin:profile }

invite:
    path:     /admin/invite
    defaults: { _controller: GrandsVoisinsBundle:Admin:invite }

organisation:
    path:     /admin/organisation
    defaults: { _controller: GrandsVoisinsBundle:Admin:organisation }

test:
    path:     testRoute
    defaults: { _controller: GrandsVoisinsBundle:Admin:test }


