# Create a routing_test just to add some route for testing ( this file is in gitignore )
grands_voisins:
    resource: "@GrandsVoisinsBundle/Resources/config/routing_test.yml"
    prefix:   /test

index:
    path:     /
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

admin:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin/
        permanent: true

home:
    path:     /admin/
    defaults: { _controller: GrandsVoisinsBundle:Admin:home }

profile:
    path:     /admin/profile
    defaults: { _controller: GrandsVoisinsBundle:Admin:profile }

createSfProfile:
    path:     /admin/createSfProfile
    defaults: { _controller: GrandsVoisinsBundle:Admin:userCreateSFProfile }

saveSfProfile:
    path:     /admin/saveSfProfile
    defaults: { _controller: GrandsVoisinsBundle:Admin:userSaveSFProfile }
team:
    path:     /admin/invite
    defaults: { _controller: GrandsVoisinsBundle:Admin:team }

organisation:
    path:     /admin/organisation
    defaults: { _controller: GrandsVoisinsBundle:Admin:organisation }

userDelete:
    path:     /admin/user/delete/{userId}
    defaults: { _controller: GrandsVoisinsBundle:Admin:userDelete }

building:
    path:     /webservice/building
    defaults: { _controller: GrandsVoisinsBundle:Webservice:building }

search:
    path:     /webservice/search
    defaults: { _controller: GrandsVoisinsBundle:Webservice:search }