index:
    path:     /
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

searchHome:
    path:     /rechercher
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

searchHomeEmpty:
    path:     /rechercher/
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

searchBuilding:
    path:     /rechercher/{building}/
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

searchBuildingTerm:
    path:     /rechercher/{building}/{term}
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

detail:
    path:     /detail
    defaults: { _controller: GrandsVoisinsBundle:WebSite:index }

admin:
    path: /mon-compte
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /mon-compte/
        permanent: true

settings:
    path:     /parametres
    defaults: { _controller: GrandsVoisinsBundle:Admin:settings }

orgaExport:
    path:     /orga-export/csv
    defaults: { _controller: GrandsVoisinsBundle:Organisation:orgaExport }

home:
    path:     /mon-compte/
    defaults: { _controller: GrandsVoisinsBundle:Admin:home }

profile:
    path:     /mon-compte/profile
    defaults: { _controller: GrandsVoisinsBundle:Admin:profile }

team:
    path:     /mon-compte/invite
    defaults: { _controller: GrandsVoisinsBundle:Admin:team }

userDelete:
    path:     /mon-compte/user/delete/{userId}
    defaults: { _controller: GrandsVoisinsBundle:Admin:userDelete }

changeAccess:
    path:    /mon-compte/access/change/{userId}/{roles}
    defaults: { _controller: GrandsVoisinsBundle:Admin:changeAccess }

orgaDelete:
    path:     /mon-compte/orga/delete/{orgaId}
    defaults: { _controller: GrandsVoisinsBundle:Organisation:orgaDelete }

fos_user_profile_show:
    path:     /mon-compte/profile
    defaults: { _controller: GrandsVoisinsBundle:Admin:profile }

webserviceParameters:
    path:     /webservice/parameters
    defaults: { _controller: GrandsVoisinsBundle:Webservice:parameters }

webserviceSearchRequest:
    path:     /webservice/searchRequest
    defaults: { _controller: GrandsVoisinsBundle:Webservice:searchRequest }

webserviceSearch:
    path:     /webservice/search
    defaults: { _controller: GrandsVoisinsBundle:Webservice:search }

webserviceLookup:
    path:     /webservice/lookup
    defaults: { _controller: GrandsVoisinsBundle:Webservice:lookup }

webserviceFieldUriSearch:
    path:     /webservice/search/field-uri
    defaults: { _controller: GrandsVoisinsBundle:Webservice:fieldUriSearch }

webserviceFieldUriLabel:
    path:     /webservice/label/field-uri
    defaults: { _controller: GrandsVoisinsBundle:Webservice:fieldUriLabel }

webserviceDetail:
    path:     /webservice/detail
    defaults: { _controller: GrandsVoisinsBundle:Webservice:detail }

all_orga:
    path:     /orga/all
    defaults: { _controller: GrandsVoisinsBundle:Organisation:all }

detail_orga:
    path:     /orga/detail
    defaults: { _controller: GrandsVoisinsBundle:Organisation:organisation }

detail_orga_edit:
    path:     /orga/detail/{orgaId}
    defaults: { _controller: GrandsVoisinsBundle:Organisation:organisation }

import:
    path:     /import
    defaults: { _controller: GrandsVoisinsBundle:Default:index }

tab:
    path:     /orga/tab
    defaults: { _controller: GrandsVoisinsBundle:Admin:allOrganization }

