services:
    grands_voisins.config:
        class: GrandsVoisinsBundle\GrandsVoisinsConfig

    GrandsVoisinsBundle.fileUploader:
        class: GrandsVoisinsBundle\Services\FileUploader
        arguments: ['%picture_directory%','%gv.domain%',]

    GrandsVoisinsBundle.formattingForm:
        class: GrandsVoisinsBundle\Services\FormattingForm
        arguments: ~

    GrandsVoisinsBundle.componentLoader:
        class: GrandsVoisinsBundle\Routing\ComponentLoader
        tags:
            - { name: routing.loader }
