services:
    grands_voisins.config:
        class: GrandsVoisinsBundle\GrandsVoisinsConfig

    GrandsVoisinsBundle.EventListener.SendMail:
        class: GrandsVoisinsBundle\Services\FileUploader
        arguments: ['%picture_directory%']
