services:
    grands_voisins.config:
        class: GrandsVoisinsBundle\GrandsVoisinsConfig

    GrandsVoisinsBundle.fileUploader:
        class: GrandsVoisinsBundle\Services\FileUploader
        arguments: ['%picture_directory%']
