parameters:

    eventConf:
      type: 'http://virtual-assembly.org/pair#Event'
      spec: 'http://assemblee-virtuelle.github.io/mmmfest/semapps-form.ttl#form-Event'
      nameType: 'event'
      fields:
        http://virtual-assembly.org/pair#subjectOf_Pair:
          value: 'subjectOfPAIR'
          access: 'anonymous'
          type: 'uri'
        http://virtual-assembly.org/pair#hasSubject_Pair:
          value: 'hasSubjectPAIR'
          access: 'anonymous'
          type: 'uri'
        http://virtual-assembly.org/pair#preferedLabel:
          value: 'preferedLabel'
          access: 'anonymous'
        http://virtual-assembly.org/pair#alternativeLabel:
          value: 'alternativeLabel'
          access: 'anonymous'
#        http://virtual-assembly.org/pair#subjectIdentifier:
#          value: 'subjectIdentifier'
#          access: 'anonymous'
        http://virtual-assembly.org/pair#description:
          value: 'description'
          access: 'anonymous'
        http://virtual-assembly.org/pair#startDate:
          value: 'startDate'
          access: 'anonymous'
        http://virtual-assembly.org/pair#endDate:
          value: 'endDate'
          access: 'anonymous'
        http://virtual-assembly.org/pair#localizedBy:
          value: 'localizedBy'
          access: 'anonymous'
#        http://virtual-assembly.org/pair#representedBy:
#          value: 'representedBy'
#          access: 'anonymous'
        http://virtual-assembly.org/pair#homePage:
          value: 'homePage'
          access: 'anonymous'
        http://virtual-assembly.org/pair#aboutPage:
          value: 'aboutPage'
          access: 'anonymous'
        http://virtual-assembly.org/pair#comment:
          value: 'comment'
          access: 'anonymous'
        http://virtual-assembly.org/pair#documentedBy:
          value: 'documentedBy'
          access: 'anonymous'
          type: 'uri'
        http://virtual-assembly.org/pair#hasSubject:
          value: 'hasSubject'
          access: 'anonymous'
          type: 'dbpedia'
        http://virtual-assembly.org/pair#hasInterest:
          value: 'hasInterest'
          access: 'anonymous'
        http://virtual-assembly.org/pair#organizedBy:
          value: 'organizedBy'
          access: 'anonymous'
          type: 'uri'
        http://virtual-assembly.org/pair#hasParticipant:
          value: 'hasParticipant'
          access: 'anonymous'
          type: 'uri'
        http://virtual-assembly.org/pair#image:
          value: 'image'
          access: 'anonymous'
        http://www.w3.org/1999/02/22-rdf-syntax-ns#type:
          value: 'type'
          access: 'anonymous'
        http://virtual-assembly.org/pair#adress:
          value: 'address'
          access: 'anonymous'
        http://virtual-assembly.org/pair#adressLine2:
          value: 'complementAddress'
          access: 'anonymous'
        http://virtual-assembly.org/pair#hasType:
          value: 'hasType'
          access: 'anonymous'
          type: 'uri'
      reverse:
        http://virtual-assembly.org/pair#organizedBy: 'http://virtual-assembly.org/pair#organizes'
        http://virtual-assembly.org/pair#hasParticipant: 'http://virtual-assembly.org/pair#participantOf'
        http://virtual-assembly.org/pair#documentedBy: 'http://virtual-assembly.org/pair#documents'
        http://virtual-assembly.org/pair#hasSubject_Pair: 'http://virtual-assembly.org/pair#subjectOf_Pair'
        http://virtual-assembly.org/pair#hasType: 'http://virtual-assembly.org/pair#typeOf'
      label:
        - http://virtual-assembly.org/pair#preferedLabel