parameters:

    organizationConf:
      type: 'http://virtual-assembly.org/pair#Organization'
      spec: 'http://assemblee-virtuelle.github.io/mmmfest/semapps-form.ttl#form-Organization'
      nameType: 'organization'
      fields:
        http://virtual-assembly.org/pair#subjectOf_Pair:
          value: 'subjectOfPAIR'
          access: 'anonymous'
        http://virtual-assembly.org/pair#preferedLabel:
          value: 'preferedLabel'
          access: 'anonymous'
        http://virtual-assembly.org/pair#alternativeLabel:
          value: 'alternativeLabel'
          access: 'anonymous'
        http://virtual-assembly.org/pair#representedBy:
          value: 'representedBy'
          access: 'anonymous'
        http://virtual-assembly.org/pair#description:
          value: 'description'
          access: 'anonymous'
        http://virtual-assembly.org/pair#comment:
          value: 'comment'
          access: 'anonymous'
        http://virtual-assembly.org/pair#homePage:
          value: 'homePage'
          access: 'anonymous'
        http://virtual-assembly.org/pair#aboutPage:
          value: 'aboutPage'
          access: 'anonymous'
        http://virtual-assembly.org/pair#hasInterest:
          value: 'hasInterest'
          access: 'anonymous'
        http://virtual-assembly.org/pair#e-mail:
          value: 'email'
          access: 'member'
        http://virtual-assembly.org/pair#phone:
          value: 'phone'
          access: 'member'
        http://virtual-assembly.org/pair#hostedIn:
          value: 'hostedIn'
          access: 'anonymous'
        http://virtual-assembly.org/pair#documentedBy:
          value: 'documentedBy'
          access: 'anonymous'
        http://virtual-assembly.org/pair#hasSubject:
          value: 'hasSubject'
          access: 'anonymous'
        http://virtual-assembly.org/pair#hasMember:
          value: 'hasMember'
          access: 'anonymous'
        http://virtual-assembly.org/pair#hasResponsible:
          value: 'hasResponsible'
          access: 'anonymous'
        http://virtual-assembly.org/pair#employs:
          value: 'employs'
          access: 'anonymous'
        http://virtual-assembly.org/pair#partnerOf:
          value: 'partnerOf'
          access: 'anonymous'
        http://virtual-assembly.org/pair#involvedIn:
          value: 'involvedIn'
          access: 'anonymous'
        http://virtual-assembly.org/pair#manages:
          value: 'manages'
          access: 'anonymous'
#        http://virtual-assembly.org/pair#operates:
#          value: 'operates'
#          access: 'anonymous'
        http://virtual-assembly.org/pair#organizes:
          value: 'organizes'
          access: 'anonymous'
        http://virtual-assembly.org/pair#participantOf:
          value: 'participantOf'
          access: 'anonymous'
        http://virtual-assembly.org/pair#offers:
          value: 'offers'
          access: 'anonymous'
        http://virtual-assembly.org/pair#needs:
          value: 'needs'
          access: 'anonymous'
        http://virtual-assembly.org/pair#brainstorms:
          value: 'brainstorms'
          access: 'anonymous'
        http://www.w3.org/1999/02/22-rdf-syntax-ns#type:
          value: 'type'
          access: 'anonymous'
        http://virtual-assembly.org/pair#image:
          value: 'image'
          access: 'anonymous'
        http://virtual-assembly.org/pair#adress:
          value: 'address'
          access: 'anonymous'
        http://virtual-assembly.org/pair#adressLine2:
          value: 'complementAddress'
          access: 'anonymous'
        http://virtual-assembly.org/pair#internal_author:
          value: 'internal_author'
          access: 'anonymous'
        http://virtual-assembly.org/pair#internal_contributor:
          value: 'internal_contributor'
          access: 'anonymous'
        http://virtual-assembly.org/pair#internal_publisher: #person + orga
           value: 'internal_publisher'
           access: 'anonymous'
        http://virtual-assembly.org/pair#hasType:
           value: 'hasType'
           access: 'anonymous'
      reverse:
        http://virtual-assembly.org/pair#hasMember: 'http://virtual-assembly.org/pair#memberOf'
        http://virtual-assembly.org/pair#hasResponsible: 'http://virtual-assembly.org/pair#responsibleOf'
        http://virtual-assembly.org/pair#employs: 'http://virtual-assembly.org/pair#employedBy'
        http://virtual-assembly.org/pair#partnerOf: 'http://virtual-assembly.org/pair#partnerOf'
        http://virtual-assembly.org/pair#documentedBy: 'http://virtual-assembly.org/pair#documents'
        http://virtual-assembly.org/pair#involvedIn: 'http://virtual-assembly.org/pair#involves'
        http://virtual-assembly.org/pair#organizes: 'http://virtual-assembly.org/pair#organizedBy'
        http://virtual-assembly.org/pair#manages: 'http://virtual-assembly.org/pair#managedBy'
        http://virtual-assembly.org/pair#participantOf: 'http://virtual-assembly.org/pair#hasParticipant'
        http://virtual-assembly.org/pair#hasType: 'http://virtual-assembly.org/pair#typeOf'
      label:
        - http://virtual-assembly.org/pair#preferedLabel