parameters:

    organizationtypeConf:
      type: 'http://www.w3.org/2004/02/skos/core#Concept'
      spec: 'http://assemblee-virtuelle.github.io/mmmfest/semapps-form.ttl#form-ThesaurusType'
      graphuri: 'urn://semapps/thesaurus/organizationtype'
      nameType: 'organizationType'
      fields:
        http://www.w3.org/2004/02/skos/core#prefLabel:
          value: 'preferedLabel'
          access: 'anonymous'
        http://www.w3.org/2004/02/skos/core#altLabel:
          value: 'alternativeLabel'
          access: 'anonymous'
        http://www.w3.org/2004/02/skos/core#definition:
          value: 'description'
          access: 'anonymous'
        http://www.w3.org/2004/02/skos/core#notation:
          value: 'comment'
          access: 'anonymous'
        http://www.w3.org/2004/02/skos/core#hasTopConcept:
          value: 'hasTopConcept'
          access: 'anonymous'
          type: 'uri'
        http://virtual-assembly.org/pair#aboutPage:
          value: 'aboutPage'
          access: 'anonymous'
        http://virtual-assembly.org/pair#homePage:
          value: 'homePage'
          access: 'anonymous'
        http://virtual-assembly.org/pair#typeOf:
          value: 'typeOf'
          access: 'anonymous'
          type: 'uri'
        http://www.w3.org/1999/02/22-rdf-syntax-ns#type:
          value: 'type'
          access: 'anonymous'
      reverse:
        http://www.w3.org/2004/02/skos/core#hasTopConcept: "http://www.w3.org/2004/02/skos/core#topConceptOf"
      label:
        - http://www.w3.org/2004/02/skos/core#prefLabel