parameters:

    personConf:
      type: 'http://virtual-assembly.org/pair#Person'
      spec: 'http://assemblee-virtuelle.github.io/mmmfest/semapps-form.ttl#form-Person'
      nameType: 'person'
      fields:
        http://virtual-assembly.org/pair#subjectOf_Pair:
          value: 'subjectOfPAIR'
          access: 'anonymous'
          type: 'uri'
        http://virtual-assembly.org/pair#firstName:
          value: 'firstName'
          access: 'anonymous'
        http://virtual-assembly.org/pair#lastName:
          value: 'lastName'
          access: 'anonymous'
        http://virtual-assembly.org/pair#alias:
          value: 'alias'
          access: 'anonymous'
#        http://virtual-assembly.org/pair#representedBy:
#          value: 'representedBy'
#          access: 'anonymous'
        http://virtual-assembly.org/pair#description:
          value: 'description'
          access: 'anonymous'
        http://virtual-assembly.org/pair#comment:
          value: 'comment'
          access: 'anonymous'
        http://virtual-assembly.org/pair#homePage:
          value: 'homePage'
          access: 'anonymous'
        http://virtual-assembly.org/pair#aboutPage:
          value: 'aboutPage'
          access: 'anonymous'
#        http://virtual-assembly.org/pair#localizedBy:
#          value: 'localizedBy'
#          access: 'anonymous'
        http://virtual-assembly.org/pair#e-mail:
          value: 'email'
          access: 'member'
        http://virtual-assembly.org/pair#phone:
          value: 'phone'
          access: 'member'
        http://virtual-assembly.org/pair#hasInterest:
          value: 'hasInterest'
          access: 'anonymous'
        http://virtual-assembly.org/pair#hasSubject:
          value: 'hasSubject'
          access: 'anonymous'
          type: 'dbpedia'
        http://virtual-assembly.org/pair#knows:
          value: 'knows'
          access: 'anonymous'
          type: 'uri'
        http://virtual-assembly.org/pair#memberOf:
          value: 'memberOf'
          access: 'anonymous'
          type: 'uri'
        http://virtual-assembly.org/pair#responsibleOf:
          value: 'responsibleOf'
          access: 'anonymous'
          type: 'uri'
        http://virtual-assembly.org/pair#affiliatedTo:
          value: 'affiliatedTo'
          access: 'anonymous'
          type: 'uri'
        http://virtual-assembly.org/pair#involvedIn:
          value: 'involvedIn'
          access: 'anonymous'
          type: 'uri'
        http://virtual-assembly.org/pair#manages:
          value: 'manages'
          access: 'anonymous'
          type: 'uri'
        http://virtual-assembly.org/pair#offers:
          value: 'offers'
          access: 'anonymous'
          type: 'dbpedia'
        http://virtual-assembly.org/pair#needs:
          value: 'needs'
          access: 'anonymous'
          type: 'dbpedia'
        http://virtual-assembly.org/pair#organizes:
          value: 'organizes'
          access: 'anonymous'
          type: 'uri'
        http://virtual-assembly.org/pair#participantOf:
          value: 'participantOf'
          access: 'anonymous'
          type: 'uri'
        http://virtual-assembly.org/pair#brainstorms:
          value: 'brainstorms'
          access: 'anonymous'
          type: 'uri'
        http://www.w3.org/1999/02/22-rdf-syntax-ns#type:
          value: 'type'
          access: 'anonymous'
        http://virtual-assembly.org/pair#image:
          value: 'image'
          access: 'anonymous'
        http://virtual-assembly.org/pair#employedBy:
          value: 'employedBy'
          access: 'anonymous'
          type: 'uri'
        http://virtual-assembly.org/pair#documentedBy:
          value: 'documentedBy'
          access: 'anonymous'
          type: 'uri'
        http://virtual-assembly.org/pair#adress:
          value: 'address'
          access: 'anonymous'
        http://virtual-assembly.org/pair#adressLine2:
          value: 'complementAddress'
          access: 'anonymous'
        http://virtual-assembly.org/pair#internal_author:
          value: 'internal_author'
          access: 'anonymous'
          type: 'uri'
        http://virtual-assembly.org/pair#internal_contributor:
          value: 'internal_contributor'
          access: 'anonymous'
          type: 'uri'
        http://virtual-assembly.org/pair#internal_publisher: #person + orga
           value: 'internal_publisher'
           access: 'anonymous'
           type: 'uri'
        http://virtual-assembly.org/pair#Skill: #person + orga
           value: 'skill'
           access: 'anonymous'
           type: 'dbpedia'

      reverse:
        http://virtual-assembly.org/pair#knows: 'http://virtual-assembly.org/pair#knows'
        http://virtual-assembly.org/pair#memberOf: 'http://virtual-assembly.org/pair#hasMember'
        http://virtual-assembly.org/pair#involvedIn: 'http://virtual-assembly.org/pair#involves'
        http://virtual-assembly.org/pair#participantOf: 'http://virtual-assembly.org/pair#hasParticipant'
        http://virtual-assembly.org/pair#manages: "http://virtual-assembly.org/pair#managedBy"
        http://virtual-assembly.org/pair#organizes: "http://virtual-assembly.org/pair#organizedBy"
        http://virtual-assembly.org/pair#responsibleOf: 'http://virtual-assembly.org/pair#hasResponsible'
        http://virtual-assembly.org/pair#employedBy: 'http://virtual-assembly.org/pair#employs'
      label:
        - http://virtual-assembly.org/pair#firstName
        - http://virtual-assembly.org/pair#lastName
