parameters:

    personConf:
      type: 'http://virtual-assembly.org/pair#Person'
      spec: 'http://assemblee-virtuelle.github.io/mmmfest/semapps-form.ttl#form-Person'
      fields:
        http://virtual-assembly.org/pair#subjectOf_Pair:
          value: 'subjectOfPAIR'
          access: 'anonymous'
        http://virtual-assembly.org/pair#firstName:
          value: 'firstName'
          access: 'anonymous'
        http://virtual-assembly.org/pair#lastName:
          value: 'lastName'
          access: 'anonymous'
        http://virtual-assembly.org/pair#alias:
          value: 'alias'
          access: 'anonymous'
        http://virtual-assembly.org/pair#representedBy:
          value: 'representedBy'
          access: 'anonymous'
        http://virtual-assembly.org/pair#description:
          value: 'description'
          access: 'anonymous'
        http://virtual-assembly.org/pair#homePage:
          value: 'homePage'
          access: 'anonymous'
        http://virtual-assembly.org/pair#aboutPage:
          value: 'aboutPage'
          access: 'anonymous'
        http://virtual-assembly.org/pair#localizedBy:
          value: 'localizedBy'
          access: 'anonymous'
        http://virtual-assembly.org/pair#e-mail:
          value: 'email'
          access: 'member'
        http://virtual-assembly.org/pair#phone:
          value: 'phone'
          access: 'member'
        http://virtual-assembly.org/pair#hasInterest:
          value: 'hasInterest'
          access: 'anonymous'
        http://virtual-assembly.org/pair#hasSubject:
          value: 'hasSubject'
          access: 'anonymous'
        http://virtual-assembly.org/pair#knows:
          value: 'knows'
          access: 'anonymous'
        http://virtual-assembly.org/pair#memberOf:
          value: 'memberOf'
          access: 'anonymous'
        http://virtual-assembly.org/pair#responsibleOf:
          value: 'responsibleOf'
          access: 'anonymous'
        http://virtual-assembly.org/pair#affiliatedTo:
          value: 'affiliatedTo'
          access: 'anonymous'
        http://virtual-assembly.org/pair#involvedIn:
          value: 'involvedIn'
          access: 'anonymous'
        http://virtual-assembly.org/pair#manages:
          value: 'manages'
          access: 'anonymous'
        http://virtual-assembly.org/pair#offers:
          value: 'offers'
          access: 'anonymous'
        http://virtual-assembly.org/pair#needs:
          value: 'needs'
          access: 'anonymous'
        http://virtual-assembly.org/pair#organizes:
          value: 'organizes'
          access: 'anonymous'
        http://virtual-assembly.org/pair#participantOf:
          value: 'participantOf'
          access: 'anonymous'
        http://virtual-assembly.org/pair#brainstorms:
          value: 'brainstorms'
          access: 'anonymous'
        http://www.w3.org/1999/02/22-rdf-syntax-ns#type:
          value: 'type'
          access: 'anonymous'
        http://virtual-assembly.org/pair#image:
          value: 'image'
          access: 'anonymous'
        http://virtual-assembly.org/pair#employedBy:
          value: 'employedBy'
          access: 'anonymous'
        http://virtual-assembly.org/pair#documentedBy:
          value: 'documentedBy'
          access: 'anonymous'
      reverse:
        http://virtual-assembly.org/pair#knows: 'http://virtual-assembly.org/pair#knows'
        http://virtual-assembly.org/pair#memberOf: 'http://virtual-assembly.org/pair#hasMember'
        http://virtual-assembly.org/pair#involvedIn: 'http://virtual-assembly.org/pair#involves'
        http://virtual-assembly.org/pair#participantOf: 'http://virtual-assembly.org/pair#hasParticipant'

    organisationConf:
      type: 'http://virtual-assembly.org/pair#Organization'
      spec: 'http://assemblee-virtuelle.github.io/mmmfest/semapps-form.ttl#form-Organization'
      fields:
        http://virtual-assembly.org/pair#subjectOf_Pair:
          value: 'subjectOfPAIR'
          access: 'anonymous'
        http://virtual-assembly.org/pair#preferedLabel:
          value: 'preferedLabel'
          access: 'anonymous'
        http://virtual-assembly.org/pair#alternativeLabel:
          value: 'alternativeLabel'
          access: 'anonymous'
        http://virtual-assembly.org/pair#representedBy:
          value: 'representedBy'
          access: 'anonymous'
        http://virtual-assembly.org/pair#description:
          value: 'description'
          access: 'anonymous'
        http://virtual-assembly.org/pair#comment:
          value: 'comment'
          access: 'anonymous'
        http://virtual-assembly.org/pair#homePage:
          value: 'homePage'
          access: 'anonymous'
        http://virtual-assembly.org/pair#aboutPage:
          value: 'aboutPage'
          access: 'anonymous'
        http://virtual-assembly.org/pair#hasInterest:
          value: 'hasInterest'
          access: 'anonymous'
        http://virtual-assembly.org/pair#e-mail:
          value: 'email'
          access: 'member'
        http://virtual-assembly.org/pair#phone:
          value: 'phone'
          access: 'member'
        http://virtual-assembly.org/pair#hostedIn:
          value: 'hostedIn'
          access: 'anonymous'
        http://virtual-assembly.org/pair#documentedBy:
          value: 'documentedBy'
          access: 'anonymous'
        http://virtual-assembly.org/pair#hasSubject:
          value: 'hasSubject'
          access: 'anonymous'
        http://virtual-assembly.org/pair#hasMember:
          value: 'hasMember'
          access: 'anonymous'
        http://virtual-assembly.org/pair#hasResponsible:
          value: 'hasResponsible'
          access: 'anonymous'
        http://virtual-assembly.org/pair#employs:
          value: 'employs'
          access: 'anonymous'
        http://virtual-assembly.org/pair#partnerOf:
          value: 'partnerOf'
          access: 'anonymous'
        http://virtual-assembly.org/pair#involvedIn:
          value: 'involvedIn'
          access: 'anonymous'
        http://virtual-assembly.org/pair#manages:
          value: 'manages'
          access: 'anonymous'
#        http://virtual-assembly.org/pair#operates:
#          value: 'operates'
#          access: 'anonymous'
        http://virtual-assembly.org/pair#organizes:
          value: 'organizes'
          access: 'anonymous'
        http://virtual-assembly.org/pair#participantOf:
          value: 'participantOf'
          access: 'anonymous'
        http://virtual-assembly.org/pair#offers:
          value: 'offers'
          access: 'anonymous'
        http://virtual-assembly.org/pair#needs:
          value: 'needs'
          access: 'anonymous'
        http://virtual-assembly.org/pair#brainstorms:
          value: 'brainstorms'
          access: 'anonymous'
        http://www.w3.org/1999/02/22-rdf-syntax-ns#type:
          value: 'type'
          access: 'anonymous'
        http://virtual-assembly.org/pair#image:
          value: 'image'
          access: 'anonymous'
      reverse:
        http://virtual-assembly.org/pair#hasMember: 'http://virtual-assembly.org/pair#memberOf'
        http://virtual-assembly.org/pair#hasResponsible: 'http://virtual-assembly.org/pair#responsibleOf'
        http://virtual-assembly.org/pair#employs: 'http://virtual-assembly.org/pair#employedBy'
        http://virtual-assembly.org/pair#partnerOf: 'http://virtual-assembly.org/pair#partnerOf'
        http://virtual-assembly.org/pair#documentedBy: 'http://virtual-assembly.org/pair#documents'

    documenttypeConf:
      type: 'http://virtual-assembly.org/pair#DocumentType'
      spec: 'http://assemblee-virtuelle.github.io/mmmfest/semapps-form.ttl#form-DocumentType'
      fields:
        http://virtual-assembly.org/pair#preferedLabel:
          value: 'preferedLabel'
          access: 'anonymous'
        http://virtual-assembly.org/pair#alternativeLabel:
          value: 'alternativeLabel'
          access: 'anonymous'
        http://virtual-assembly.org/pair#description:
          value: 'description'
          access: 'anonymous'
        http://virtual-assembly.org/pair#comment:
          value: 'comment'
          access: 'anonymous'
        http://virtual-assembly.org/pair#aboutPage:
          value: 'aboutPage'
          access: 'anonymous'
        http://virtual-assembly.org/pair#homePage:
          value: 'homePage'
          access: 'anonymous'
        http://virtual-assembly.org/pair#typeOf:
          value: 'typeOf'
          access: 'anonymous'
        http://www.w3.org/1999/02/22-rdf-syntax-ns#type:
          value: 'type'
          access: 'anonymous'
      reverse: null
      label:
        - http://virtual-assembly.org/pair#preferedLabel
    documentConf:
      type: 'http://virtual-assembly.org/pair#Document'
      spec: 'http://assemblee-virtuelle.github.io/mmmfest/semapps-form.ttl#form-Document'
      fields:
        http://virtual-assembly.org/pair#subjectOf_Pair:
          value: 'subjectOfPAIR'
          access: 'anonymous'
        http://virtual-assembly.org/pair#preferedLabel:
          value: 'preferedLabel'
          access: 'anonymous'
        http://virtual-assembly.org/pair#alternativeLabel:
          value: 'alternativeLabel'
          access: 'anonymous'
        http://virtual-assembly.org/pair#description:
          value: 'description'
          access: 'anonymous'
        http://virtual-assembly.org/pair#comment:
          value: 'comment'
          access: 'anonymous'
        http://virtual-assembly.org/pair#aboutPage:
          value: 'aboutPage'
          access: 'anonymous'
        http://virtual-assembly.org/pair#homePage:
          value: 'homePage'
          access: 'anonymous'
#        http://virtual-assembly.org/pair#represents:
#          value: 'represents'
#          access: 'anonymous'
        http://virtual-assembly.org/pair#documents:
          value: 'documents'
          access: 'anonymous'
        http://virtual-assembly.org/pair#references:
          value: 'references'
          access: 'anonymous'
        http://virtual-assembly.org/pair#referencesBy:
          value: 'referencesBy'
          access: 'anonymous'
        http://virtual-assembly.org/pair#hasType:
          value: 'hasType'
          access: 'anonymous'
        http://www.w3.org/1999/02/22-rdf-syntax-ns#type:
          value: 'type'
          access: 'anonymous'
        http://virtual-assembly.org/pair#internal_author:
          value: 'internal_author'
          access: 'anonymous'
        http://virtual-assembly.org/pair#internal_contributor:
          value: 'internal_contributor'
          access: 'anonymous'
        http://virtual-assembly.org/pair#format:
           value: 'format'
           access: 'anonymous'
        http://virtual-assembly.org/pair#language:
           value: 'language'
           access: 'anonymous'
        http://virtual-assembly.org/pair#licence:
           value: 'licence'
           access: 'anonymous'
        http://virtual-assembly.org/pair#publicationDate:
           value: 'publicationDate'
           access: 'anonymous'
#        http://virtual-assembly.org/pair#source:
#           value: 'source'
#           access: 'anonymous'
#        http://virtual-assembly.org/pair#version:
#           value: 'version'
#           access: 'anonymous'
      reverse:
        http://virtual-assembly.org/pair#references: 'http://virtual-assembly.org/pair#referencesBy'
        http://virtual-assembly.org/pair#hasType: 'http://virtual-assembly.org/pair#typeOf'
        http://virtual-assembly.org/pair#documents: 'http://virtual-assembly.org/pair#documentedBy'
      label:
        - http://virtual-assembly.org/pair#preferedLabel
    projectConf:
      type: 'http://virtual-assembly.org/pair#Project'
      spec: 'http://assemblee-virtuelle.github.io/mmmfest/semapps-form.ttl#form-Project'
      fields:
        http://virtual-assembly.org/pair#subjectOf_Pair:
          value: 'subjectOfPAIR'
          access: 'anonymous'
        http://virtual-assembly.org/pair#preferedLabel:
          value: 'preferedLabel'
          access: 'anonymous'
        http://virtual-assembly.org/pair#alternativeLabel:
          value: 'alternativeLabel'
          access: 'anonymous'
        http://virtual-assembly.org/pair#description:
          value: 'description'
          access: 'anonymous'
        http://virtual-assembly.org/pair#comment:
          value: 'comment'
          access: 'anonymous'
        http://virtual-assembly.org/pair#homePage:
          value: 'homePage'
          access: 'anonymous'
        http://virtual-assembly.org/pair#aboutPage:
          value: 'aboutPage'
          access: 'anonymous'
#        http://virtual-assembly.org/pair#concretizes:
#          value: 'concretizes'
#          access: 'anonymous'
        http://virtual-assembly.org/pair#managedBy:
          value: 'managedBy'
          access: 'anonymous'
#        http://virtual-assembly.org/pair#representedBy:
#          value: 'representedBy'
#          access: 'anonymous'
        http://virtual-assembly.org/pair#offers:
          value: 'offers'
          access: 'anonymous'
        http://virtual-assembly.org/pair#needs:
          value: 'needs'
          access: 'anonymous'
        http://virtual-assembly.org/pair#involves:
          value: 'involves'
          access: 'anonymous'
        http://virtual-assembly.org/pair#documentedBy:
          value: 'documentedBy'
          access: 'anonymous'
#        http://virtual-assembly.org/pair#delivers:
#          value: 'delivers'
#          access: 'anonymous'
        http://virtual-assembly.org/pair#hasSubject:
          value: 'hasSubject'
          access: 'anonymous'
#        http://virtual-assembly.org/pair#subjectOf:
#          value: 'subjectOf'
#          access: 'anonymous'
        http://virtual-assembly.org/pair#hasInterest:
          value: 'hasInterest'
          access: 'anonymous'
        http://virtual-assembly.org/pair#image:
          value: 'image'
          access: 'anonymous'
        http://www.w3.org/1999/02/22-rdf-syntax-ns#type:
          value: 'type'
          access: 'anonymous'
      reverse:
#        http://virtual-assembly.org/pair#concretizes : 'http://virtual-assembly.org/pair#concretizedBy'
        http://virtual-assembly.org/pair#managedBy: 'http://virtual-assembly.org/pair#manages'
        http://virtual-assembly.org/pair#involves: 'http://virtual-assembly.org/pair#involvedIn'
        http://virtual-assembly.org/pair#documentedBy: 'http://virtual-assembly.org/pair#documents'
      label:
        - http://virtual-assembly.org/pair#preferedLabel

    eventConf:
      type: 'http://virtual-assembly.org/pair#Event'
      spec: 'http://assemblee-virtuelle.github.io/mmmfest/semapps-form.ttl#form-Event'
      fields:
        http://virtual-assembly.org/pair#subjectOf_Pair:
          value: 'subjectOfPAIR'
          access: 'anonymous'
        http://virtual-assembly.org/pair#preferedLabel:
          value: 'preferedLabel'
          access: 'anonymous'
        http://virtual-assembly.org/pair#alternativeLabel:
          value: 'alternativeLabel'
          access: 'anonymous'
#        http://virtual-assembly.org/pair#subjectIdentifier:
#          value: 'subjectIdentifier'
#          access: 'anonymous'
        http://virtual-assembly.org/pair#description:
          value: 'description'
          access: 'anonymous'
        http://virtual-assembly.org/pair#startDate:
          value: 'startDate'
          access: 'anonymous'
        http://virtual-assembly.org/pair#endDate:
          value: 'endDate'
          access: 'anonymous'
        http://virtual-assembly.org/pair#localizedBy:
          value: 'localizedBy'
          access: 'anonymous'
#        http://virtual-assembly.org/pair#representedBy:
#          value: 'representedBy'
#          access: 'anonymous'
        http://virtual-assembly.org/pair#homePage:
          value: 'homePage'
          access: 'anonymous'
        http://virtual-assembly.org/pair#aboutPage:
          value: 'aboutPage'
          access: 'anonymous'
        http://virtual-assembly.org/pair#comment:
          value: 'comment'
          access: 'anonymous'
        http://virtual-assembly.org/pair#documentedBy:
          value: 'documentedBy'
          access: 'anonymous'
        http://virtual-assembly.org/pair#hasSubject:
          value: 'hasSubject'
          access: 'anonymous'
        http://virtual-assembly.org/pair#hasInterest:
          value: 'hasInterest'
          access: 'anonymous'
        http://virtual-assembly.org/pair#organizedBy:
          value: 'organizedBy'
          access: 'anonymous'
        http://virtual-assembly.org/pair#hasParticipant:
          value: 'hasParticipant'
          access: 'anonymous'
        http://virtual-assembly.org/pair#image:
          value: 'image'
          access: 'anonymous'
        http://www.w3.org/1999/02/22-rdf-syntax-ns#type:
          value: 'type'
          access: 'anonymous'
      reverse:
        http://virtual-assembly.org/pair#organizedBy: 'http://virtual-assembly.org/pair#organizes'
        http://virtual-assembly.org/pair#hasParticipant: 'http://virtual-assembly.org/pair#participantOf'
        http://virtual-assembly.org/pair#documentedBy: 'http://virtual-assembly.org/pair#documents'
      label:
        - http://virtual-assembly.org/pair#preferedLabel
    proposalConf:
      type: 'http://virtual-assembly.org/pair#Proposal'
      spec: 'http://assemblee-virtuelle.github.io/mmmfest/semapps-form.ttl#form-Proposal'
      fields:
        http://virtual-assembly.org/pair#hasSubject_Pair:
          value: 'hasSubjectPAIR'
          access: 'anonymous'
        http://virtual-assembly.org/pair#preferedLabel:
          value: 'preferedLabel'
          access: 'anonymous'
        http://virtual-assembly.org/pair#alternativeLabel:
          value: 'alternativeLabel'
          access: 'anonymous'
#        http://virtual-assembly.org/pair#subjectIdentifier:
#          value: 'subjectIdentifier'
#          access: 'anonymous'
        http://virtual-assembly.org/pair#description:
          value: 'description'
          access: 'anonymous'
        http://virtual-assembly.org/pair#comment:
          value: 'comment'
          access: 'anonymous'
        http://virtual-assembly.org/pair#aboutPage:
          value: 'aboutPage'
          access: 'anonymous'
        http://virtual-assembly.org/pair#homePage:
          value: 'homePage'
          access: 'anonymous'
        http://virtual-assembly.org/pair#brainstormedBy:
          value: 'brainstormedBy'
          access: 'anonymous'
        http://virtual-assembly.org/pair#concretizedBy:
          value: 'concretizedBy'
          access: 'anonymous'
#        http://virtual-assembly.org/pair#representedBy:
#          value: 'representedBy'
#          access: 'anonymous'
        http://virtual-assembly.org/pair#documentedBy:
          value: 'documentedBy'
          access: 'anonymous'
        http://virtual-assembly.org/pair#hasSubject:
          value: 'hasSubject'
          access: 'anonymous'
        http://virtual-assembly.org/pair#hasInterest:
          value: 'hasInterest'
          access: 'anonymous'
        http://virtual-assembly.org/pair#image:
          value: 'image'
          access: 'anonymous'
        http://www.w3.org/1999/02/22-rdf-syntax-ns#type:
          value: 'type'
          access: 'anonymous'
      reverse:
        http://virtual-assembly.org/pair#brainstormedBy: 'http://virtual-assembly.org/pair#brainstorms'
        http://virtual-assembly.org/pair#documentedBy: 'http://virtual-assembly.org/pair#documents'
        http://virtual-assembly.org/pair#hasSubject_Pair: 'http://virtual-assembly.org/pair#subjectOf_Pair'
      label:
        - http://virtual-assembly.org/pair#preferedLabel